# Generated by Django 3.1 on 2020-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(max_length=12, unique=True)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
            ],
        ),
    ]
